# Find a way to make ths more compact
name = input ("Enter your name: ")
age = input ("Enter your age: ")
gender = input ("Enter your gender: ")
school = input ("What university do you attend?: ")
day = input ("How is your day today?: ")
candy = input ("What is your candy?: ")
drink = input ("What is your favortie drink?: ")
color = input ("What is your favorite color?: ")
mood = input ("Are you good?: ")
vibe = input ("Are we vibing?: ")
print ("Name:", name)
print ("Age:", age)
print ("Gender:", gender)
print ("School:", school)
print ("Status:", day)
print ("Favorite Candy:", candy)
print ("Favorite Drink:", drink)
print ("Favorite Color:", color)
print ("Current Mood:", mood)
print ("Vibe Check:", vibe)